spring.application.name=Payment-Gateway
server.port=${PORT:4444}


eureka.client.service-url.defaultZone=https://stripe-service-registry.onrender.com/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true



spring.cloud.gateway.routes[0].id=Stripe-Processing-Service
spring.cloud.gateway.routes[0].uri=lb://Stripe-Processing-Service
spring.cloud.gateway.routes[0].predicates[0]=Path=/v1/payments/**




